function strtrim(t) { return t.replace(/^\s+|\s+$/gm, "") }
var $t;

function calculate() { var t = parseFloat($("#input-capital").val()),
        e = parseFloat($("#input-tax").val()) / 100 * t + t;
    $("#total-item-price").val(e) }
$(document).on("click", ".open-details", function() { var t = $(this);
    $(".item-data").remove(), $(".details-toggle").html('<i class="fa fa-plus-circle" aria-hidden="true"></i>'), $(".details-toggle").addClass("open-details"), $(".details-toggle").removeClass("close-details"), t.html('<i class="fa fa-minus-circle" aria-hidden="true"></i>'), t.addClass("close-details"), t.removeClass("open-details"), $.ajax({ url: url(window.location.href) + "/includes/item-details.php", method: "POST", data: { id: $(this).children().first().text() }, success: function(e) { var a = $(e);
            t.parent().children(".child").hide(), t.parent().parent().after(a), a.show("slow") } }) }), $(document).on("click", ".close-details", function() { $(".item-data").remove(), $(this).html('<i class="fa fa-plus-circle" aria-hidden="true"></i>'), $(this).addClass("open-details"), $(this).removeClass("close-details") }), $(document).ready(function() { $t = $("#example").DataTable({ responsive: !0 }) }), $(document).on("click", "#confirm-delete", function() { var t = $(this).val();
    $.ajax({ url: url(window.location.href) + "/controller/delete-item.php", method: "POST", data: { submit: "submit", item_id: t }, success: function(t) { var e = JSON.parse(t);
            $(".alert").addClass("alert" + e.status), $(".alert").text(e.message), $(".alert").fadeTo(3e3, 500).slideUp(500, function() { $(".alert").slideUp(500), location.reload() }) } }) }), $(document).on("click", ".delete", function() { var t = $(this).val();
    $(".alert").alert("show"), $("#exampleModalLabel").text("Please Confirm Item Delete"), $(".modal-body").html("<b>Item Name:</b> " + $("#name" + t).val() + "</br><b>Item Brand:</b> " + $("#brand" + t).val() + "</br><b>Description:</b> " + $("#desc" + t).val() + "</br>"), $(".modal-footer").html('<button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button><button class="btn btn-primary" value="' + t + '" data-dismiss="modal" id="confirm-delete" >Delete</button>') }), $(document).on("click", ".update", function() { $(".toast").toast("show"); var t = $(this).val();
    $.ajax({ url: url(window.location.href) + "/controller/edit-item.php", method: "POST", data: { submit: "submit", item_id: t, item_capital: parseFloat($("#capital" + t).text()).toFixed(2), item_name: strtrim($("#name" + t).text()), item_brand: strtrim($("#brand" + t).text()), item_tax: parseFloat($("#tax" + t).text()).toFixed(2), item_desc: strtrim($("#desc" + t).text()), item_category: $("#cat" + t).attr("cat-id") }, success: function(t) { var e = JSON.parse(t);
            $(".alert").addClass("alert" + e.status), $(".alert").text(e.message), $(".alert").fadeTo(3e3, 500).slideUp(500, function() { $(".alert").slideUp(500) }) } }) }), $(document).on("change", ".custom-file-input", function(t) { var e = $("input[type=file]").val().split("\\").pop(),
        a = ""; if (e.length > 20) a = e.substring(0, 20) + " ...";
    $(".custom-file-label").text(a) }), $(document).on("input", "#input-capital", function() { calculate() }), $(document).on("input", "#input-tax", function() { calculate() });