var $t, $replace, $id, $purchased_id;
$(document).ready(function() { $t = $("#example").DataTable() }), $(document).on("hidden.bs.modal", "#transmodal", function() { $.ajax({ url: url(window.location.href) + "/controller/get-transactions.php", method: "GET", success: function(e) { $("#data-trans").html(e), $t = $("#example").DataTable() } }) }), $(document).on("click", ".open", function() { $replace = !1, $id = $(this).val(), $.ajax({ url: url(window.location.href) + "/controller/return-controller.php", method: "POST", data: { id: $id, type: "open" }, success: function(e) { var t = JSON.parse(e);
            $(".modal-body").html(""), t.forEach(function(e) { var t = (parseFloat(e.item_tax) / 100 * parseFloat(e.item_price) + parseFloat(e.item_price)).toFixed(2);
                $("#transmodalLabel").text("Transaction: " + e.transaction_id), $(".modal-body").append('<div class="card p-2 mb-2"><div class="alert alert-success" style="display: none" role="alert" id="alert_' + e.purchased_id + '"></div><div class="d-flex mb-2"><img width="100" style="max-heigth: 100px" src="img/item/' + e.item_img + '" alt=""><div class="p-2"><p><b>Name:&nbsp;</b>' + e.item_name + "</p><p><b>Brand:&nbsp;</b>" + e.item_brand + '</p><p unit="' + e.item_unit + '" id="item_count_' + e.purchased_id + '"><b>' + e.item_unit + ":&nbsp;</b>" + e.item_count + "</p><p><b>Price:&nbsp;</b>₱" + t + "</p><p><b>Total:&nbsp;</b>₱" + t * e.item_count + '</p></div></div><div class="d-flex mb-2"><input class="form-control m-2 void-count" type="number" item_count="' + e.item_count + '" /><button style="width: 100%;" class="void btn btn-warning m-2" value="' + e.item_id + '" purchased_void_id="' + e.purchased_id + '">Void</button><button style="width: 100%;" class="damage btn btn-danger m-2" value="' + e.item_id + '" purchased_damage_id="' + e.purchased_id + '">Damage</button><div class="form-check m-2"><input type="checkbox" class="form-check-input" id="replace_' + e.purchased_id + '"><label class="form-check-label" for="replace">Replace Damaged</label></div></div> </div> ') }) } }) }), $(document).on("input", ".void-count", function() { var e = $(this).attr("item_count");
    e - $(this).val() < 0 && $(this).val(e) }), $(document).on("change", ".form-check-input", function() { $replace = 0 == $replace }), $(document).on("click", ".void", function() { var e = $(this); if ("" == $(this).prev().prev().val()) $(this).prev().prev().focus();
    else { var t = $(this).val();
        $purchased_id = $(this).attr("purchased_void_id"); var a = $(this).prev().val();
        $.ajax({ url: url(window.location.href) + "/controller/cc-controller.php", method: "POST", data: { submit: "void", purchased_id: $purchased_id, item_id: t, item_count: a }, success: function(t) { var a = JSON.parse(t);
                e.parent().prev().prev().html(a.message), e.parent().prev().prev().attr("class", "alert alert-" + a.status), e.parent().prev().prev().fadeTo(3e3, 500).slideUp(500, function() { $(".modal-body").html(""), $.ajax({ url: url(window.location.href) + "/controller/return-controller.php", method: "POST", data: { id: $id, type: "open" }, success: function(e) { var t = JSON.parse(e);
                            $(".modal-body").html(""), t.forEach(function(e) { var t = (parseFloat(e.item_tax) / 100 * parseFloat(e.item_price) + parseFloat(e.item_price)).toFixed(2);
                                $("#transmodalLabel").text("Transaction: " + e.transaction_id), $(".modal-body").append('<div class="card p-2 mb-2"><div class="alert alert-success" style="display: none" role="alert" id="alert_' + e.purchased_id + '"></div><div class="d-flex mb-2"><img width="100" style="max-heigth: 100px" src="img/item/' + e.item_img + '" alt=""><div class="p-2"><p><b>Name:&nbsp;</b>' + e.item_name + "</p><p><b>Brand:&nbsp;</b>" + e.item_brand + '</p><p unit="' + e.item_unit + '" id="item_count_' + e.purchased_id + '"><b>' + e.item_unit + ":&nbsp;</b>" + e.item_count + "</p><p><b>Price:&nbsp;</b>₱" + t + "</p><p><b>Total:&nbsp;</b>₱" + t * e.item_count + '</p></div></div><div class="d-flex mb-2"><input class="form-control m-2 void-count" type="number" item_count="' + e.item_count + '" /><button style="width: 100%;" class="void btn btn-warning m-2" value="' + e.item_id + '" purchased_void_id="' + e.purchased_id + '">Void</button><button style="width: 100%;" class="damage btn btn-danger m-2" value="' + e.item_id + '" purchased_damage_id="' + e.purchased_id + '">Damage</button><div class="form-check m-2"><input type="checkbox" class="form-check-input" id="replace_' + e.purchased_id + '"><label class="form-check-label" for="replace">Replace Damaged</label></div></div> </div> ') }) } }) }) } }) } }), $(document).on("click", ".damage", function() { if ("" == $(this).prev().prev().val()) $(this).prev().prev().focus();
    else { var e = $(this),
            t = $(this).val();
        $purchased_id = $(this).attr("purchased_damage_id"); var a = $(this).prev().prev().val();
        $.ajax({ url: url(window.location.href) + "/controller/cc-controller.php", method: "POST", data: { submit: "damage", purchased_id: $purchased_id, item_id: t, item_count: a, replace: $replace }, success: function(t) { var a = JSON.parse(t);
                e.parent().prev().prev().html(a.message), e.parent().prev().prev().attr("class", "alert alert-" + a.status), e.parent().prev().prev().fadeTo(3e3, 500).slideUp(500, function() { $(".modal-body").html(""), $.ajax({ url: url(window.location.href) + "/controller/return-controller.php", method: "POST", data: { id: $id, type: "open" }, success: function(e) { var t = JSON.parse(e);
                            $(".modal-body").html(""), t.forEach(function(e) { var t = (parseFloat(e.item_tax) / 100 * parseFloat(e.item_price) + parseFloat(e.item_price)).toFixed(2);
                                $("#transmodalLabel").text("Transaction: " + e.transaction_id), $(".modal-body").append('<div class="card p-2 mb-2"><div class="alert alert-success" style="display: none" role="alert" id="alert_' + e.purchased_id + '"></div><div class="d-flex mb-2"><img width="100" style="max-heigth: 100px" src="img/item/' + e.item_img + '" alt=""><div class="p-2"><p><b>Name:&nbsp;</b>' + e.item_name + "</p><p><b>Brand:&nbsp;</b>" + e.item_brand + '</p><p unit="' + e.item_unit + '" id="item_count_' + e.purchased_id + '"><b>' + e.item_unit + ":&nbsp;</b>" + e.item_count + "</p><p><b>Price:&nbsp;</b>₱" + t + "</p><p><b>Total:&nbsp;</b>₱" + t * e.item_count + '</p></div></div><div class="d-flex mb-2"><input class="form-control m-2 void-count" type="number" item_count="' + e.item_count + '" /><button style="width: 100%;" class="void btn btn-warning m-2" value="' + e.item_id + '" purchased_void_id="' + e.purchased_id + '">Void</button><button style="width: 100%;" class="damage btn btn-danger m-2" value="' + e.item_id + '" purchased_damage_id="' + e.purchased_id + '">Damage</button><div class="form-check m-2"><input type="checkbox" class="form-check-input" id="replace_' + e.purchased_id + '"><label class="form-check-label" for="replace">Replace Damaged</label></div></div> </div> ') }) } }) }) } }) } });